<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resultat
[
    <!ELEMENT resultat (album)>
    <!ATTLIST resultat tema CDATA #REQUIRED>
    <!ELEMENT album (nombre,escritor,fecha,cancion+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT escritor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT cancion (titulo,genero,autor,duracion)>
    <!ATTLIST cancion id CDATA #REQUIRED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT duracion (#PCDATA)>
]>
<resultat tema="xml">
    <album>
        <nombre>Carrer Salut</nombre>
        <escritor>Compay Segundo</escritor>
        <fecha>Març de 1999</fecha>
        <cancion id="1">
            <titulo>Salutació a Chango</titulo>
            <genero>Són-afro</genero>
            <autor>Armant Dulfo</autor>
            <duracion>5’46’’</duracion>
        </cancion>
        <cancion id="2">
            <titulo>Amor Gegant</titulo>
            <genero>Bolero-són </genero>
            <autor>Francisco Repilado</autor>
            <duracion>2’52’’</duracion>
        </cancion>
        <cancion id="3">
            <titulo>Rosa de França </titulo>
            <genero>Bolero-són</genero>
            <autor>Rodrigo Prats</autor>
            <duracion>5’20’’</duracion>
        </cancion>
        <cancion id="4">
            <titulo>María a la Platja</titulo>
            <genero>Merenga</genero>
            <autor>Francisco Repilado</autor>
            <duracion>2’49’’</duracion>
        </cancion>
        <cancion id="5">
            <titulo>Versos per a Tu</titulo>
            <genero>Bolero-són</genero>
            <autor>Francisco Repilado</autor>
            <duracion>3’56’’</duracion>
        </cancion>
        <cancion id="6">
            <titulo>La Engañadora</titulo>
            <genero>Bolero-són</genero>
            <autor>Enrique Jorrín</autor>
            <duracion>4’20’’</duracion>
        </cancion>
        <cancion id="7">
            <titulo>Vells sons de Santiago</titulo>
            <genero>Són</genero>
            <autor>Popular</autor>
            <duracion>4’21’’</duracion>
        </cancion>
        <cancion id="8">
            <titulo>El Dia que em Vulgues</titulo>
            <genero>Bolero</genero>
            <autor>Carlos Gardél</autor>
            <duracion>4’03’’</duracion>
        </cancion>
        <cancion id="9">
            <titulo>Es Va perdre la Flauta </titulo>
            <genero>Saborós</genero>
            <autor>Compay Segundo</autor>
            <duracion>4’52’’</duracion>
        </cancion>
        <cancion id="10">
            <titulo>Morir d'Amor</titulo>
            <genero>Bolero</genero>
            <autor>Xarres Aznavour</autor>
            <duracion>3’29’’</duracion>
        </cancion>
        <cancion id="11">
            <titulo>Llàgrimes Negres</titulo>
            <genero>Són</genero>
            <autor>Miguel Matamoros </autor>
            <duracion>3’49’’</duracion>
        </cancion>
        <cancion id="12">
            <titulo>Balcó de Santiago</titulo>
            <genero>Són</genero>
            <autor>Francisco Repilado</autor>
            <duracion>5’40’’</duracion>
        </cancion>
        <cancion id="13">
            <titulo>Chan Chan</titulo>
            <genero>Són</genero>
            <autor>Francisco Repilado</autor>
            <duracion>5’30’’</duracion>
        </cancion>
    </album>
</resultat>