<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resultat
[
    <!ELEMENT resultat (libreria+)>
    <!ATTLIST resultat tema CDATA #REQUIRED>
    <!ELEMENT libreria (nombre,url,libro+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT url (#PCDATA)>
    <!ELEMENT libro (isbn,nivel,titulo,autor,editorial,any,web,precio)>
    <!ELEMENT isbn (#PCDATA)>
    <!ELEMENT nivel (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT any (#PCDATA)>
    <!ELEMENT web (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
]>
<resultat tema="xml">
    <libreria>
        <nombre>Casa del libro</nombre>
        <url>www.casadellibro.com</url>
        <libro>
            <isbn>ISBN9788493272074</isbn>
            <nivel>avançat</nivel>
            <titulo>SERIE DESENVOLUPADORS: APLICACIONS XML AMB XML SUITE</titulo>
            <autor>diversos autors</autor>
            <editorial>DANYSOFT 2006</editorial>
            <any>2006</any>
            <web>http://www.casadellibro.com/libro-serie-desarrolladores-aplicaciones-xml-conxml-suite/1096337/2900001128466</web>
            <precio>50.96€</precio>
        </libro>
        <libro>
            <isbn>ISBN9782746049581</isbn>
            <nivel>Avançat</nivel>
            <titulo>LLIBRES - XML PRACTIQUE. BASES ESSENCIALS, CONCEPTES I CASOS PRACTICOS</titulo>
            <autor>BOULANGER, THIERRY</autor>
            <editorial>ENI</editorial>
            <any>2009</any>
            <web>http://www.casadellibro.com/libro-xml-practico-bases-esenciales-conceptos-ycasos-practicos/1261538/2900001325392</web>
            <precio>26.95€</precio>
        </libro>
        <libro>
            <isbn>ISBN9788441525924</isbn>
            <nivel>intermedi</nivel>
            <titulo>DESENVOLUPAMENT D'APLICACIONS WEB DINAMICAS XML I JAVA</titulo>
            <autor>PARSONS, DAVID</autor>
            <editorial>ANAYA</editorial>
            <any>2009</any>
            <web>http://www.casadellibro.com/libro-desarrollo-de-aplicaciones-web-dinamicasxml-y-java-incluye-cd-programacion/1260111/2900001323752</web>
            <precio>52.70€</precio>
        </libro>
        <libro>
            <isbn>ISBN9788441524255</isbn>
            <nivel>avançat</nivel>
            <titulo>SERIE DESENVOLUPADORS: APLICACIONS XML AMB XML SUITE</titulo>
            <autor>PARSONS, DAVID</autor>
            <editorial>ANAYA</editorial>
            <any>2008</any>
            <web>http://www.casadellibro.com/libro-indesign-con-xml-para-disenadores-diseno-ycreatividad/1205682/2900001260950</web>
            <precio>25.60€</precio>
        </libro>
    </libreria>
    <libreria>
        <nombre>Amazon</nombre>
        <url>www.amazon.com</url>
        <libro>
            <isbn>ISBN9780231559678</isbn>
            <nivel>avançat</nivel>
            <titulo>XML: Visual QuickStart Guide (2nd Edition)</titulo>
            <autor>Kevin Howard Goldberg</autor>
            <editorial>PEACHPIT PRESS</editorial>
            <any>2009</any>
            <web>http://www.amazon.com/xml-visual-quickstart-guide2nd/dp/0321559673/ref=sr_1_1?ie=utf8s=booksqid=1253090976sr=1-1</web>
            <precio>23.09$</precio>
        </libro>
        <libro>
            <isbn>ISBN9780470114872</isbn>
            <nivel>avançat</nivel>
            <titulo>Beginning XML, 4th Edition</titulo>
            <autor>David Hunter, Jeff Rafter, Joe Fawcett, Eric van der Vlist, Danny Ayers, Jon
                    Duckett , Andrew Watt i Linda McKinnon 
            </autor>
            <editorial>Wiley Publishing</editorial>
            <any>2007</any>
            <web>http://www.amazon.com/beginning-xml-4thprogrammer/dp/0470114878/ref=sr_1_2?ie=utf8s=booksqid=1253090976sr=1-2</web>
            <precio>26.39$</precio>
        </libro>
        <libro>
            <isbn>ISBN9780596004200</isbn>
            <nivel>avançat</nivel>
            <titulo>Learning XML, Second Edition</titulo>
            <autor>Erik Ray</autor>
            <editorial>O'Reilly</editorial>
            <any>2003</any>
            <web>http://www.amazon.com/learning-xml-second-erikray/dp/0596004206/ref=sr_1_3?ie=utf8s=booksqid=1253090976sr=1-3#reader</web>
            <precio>21.50$</precio>
        </libro>
    </libreria>
</resultat>